### PR TITLE
Add support for Doorkeeper 5.4

### PR DESCRIPTION
**Pull request by gencer**
This adds ORM changes to support Doorkeeper 5.4

### CODE REVIEW

**Comment by gencer** [comment]
Hi @nbulaj something is preventing from being tested on TravisCI.

**Update**:

I've setup my own travis and see that there is a method called `with_lock` in token call. I cannot find any reference so when i debug there i see that its came from `ActiveRecord`. So, I just added similar code block to replicate same lock feature in Sequel.

See here: https://github.com/gencer/doorkeeper-sequel/blob/doorkeeper-5.4/lib/doorkeeper-sequel/mixins/concerns/sequel_compat.rb#L44

CI passes: https://travis-ci.org/github/gencer/doorkeeper-sequel/builds/671223953

**Review by nbulaj — APPROVED** [review]
:monorail:

**Comment by gencer** [comment]
I forgot to remove duplicate code block `with_lock` from mixin. Just pushed.

See: https://travis-ci.org/github/gencer/doorkeeper-sequel/builds/671329427

Thanks for the appoval.

P.S.: Please rebase your local copy if you pull earlier.

**Review by nbulaj — APPROVED** [review]

**Comment by nbulaj** [comment]
Thanks @gencer ! :tada:

**Pull request merged**
